.TH PHPMETRICS 1
.SH NAME
phpmetrics \- static analysis for PHP
.SH SYNOPSIS
.B phpmetrics
[\fB\-\-report\-html=\fR\fIPATH\fR]
.IR file_or_directory ...
.SH DESCRIPTION
.B phpmetrics
executes a static analysis on PHP (PHP 5 to PHP 7 included) code and provides various reports (HTML, XML, JSON...).
.SH OPTIONS
.TP
.BR \-h ", " \-\-help\fI
Display help.
.TP
.BR \-\-report-html =\fIdirectory
Path to save report in HTML format. Example: /tmp/my-directory
.TP
.BR \-\-report-violations =\fIfilename
Path to save violations in XML format. Example: /tmp/report.xml
.TP
.BR \-\-extensions =\fIextension1,extension2
Extensions to include, separated by comma (,)
.TP
.BR \-\-exclude =\fIdirectory1,directory2
Subdirectories to exclude
.TP
.BR \-\-symlinks
Enable following symlinks
.TP
.BR \-q ", " \-\-quiet\fI
Do not output any message.
.TP
.BR \-V ", " \-\-version\fI
Display version of PhpMetrics
